import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#F6F5F2]">
      <section className="bg-[#0F2E46] text-white py-20">
        <div className="max-w-7xl mx-auto px-6">
          <h1 className="text-5xl font-bold">Privacy Policy</h1>
          <p className="mt-6 max-w-3xl text-white/80 leading-8">
  At DigiNiwas, we are committed to protecting your privacy and ensuring
  transparency in how your information is collected and used. This Privacy
  Policy explains how we collect, use, store and protect your personal
  information when you access or use the DigiNiwas platform, including
  Niwas AI and our related property services.
</p>
        </div>
      </section>

      <main className="max-w-7xl mx-auto px-6 py-12 space-y-8">
      {[
  [
    "Information We Collect",
    `We may collect the following information:

• Name
• Email address
• Mobile number
• Property preferences
• Saved listings and favourites
• Search history
• Approximate location (with your permission)
• Property enquiries
• Conversations with Niwas AI
• Device information, browser type and IP address for security and analytics`
  ],

  [
    "How We Use Your Information",
    `We use your information to:

• Recommend relevant properties
• Connect buyers, sellers, tenants, landlords and verified property professionals
• Improve Niwas AI recommendations and platform features
• Respond to customer enquiries and support requests
• Prevent fraud and enhance platform security
• Send important service updates and notifications
• Comply with legal and regulatory requirements`
  ],

  [
    "Property Listings",
    `DigiNiwas acts as a technology platform that facilitates property discovery and connections between users.
While we encourage accurate listings, property owners, builders, developers and agents are solely responsible for the information they publish.
Users are advised to independently verify all property details, legal documents and ownership before making any financial or legal decisions.`
  ],

  [
    "Niwas AI",
    `Niwas AI provides AI-powered property recommendations and informational assistance.

The information generated by Niwas AI is intended for general guidance only and should not be considered legal, financial, tax, investment or professional advice.

AI Disclaimer:
Niwas AI provides automated recommendations based on available information. Users should independently verify all property details and consult qualified professionals before making financial, legal or investment decisions.`
  ],

  [
    "Cookies & Analytics",
    `We use cookies and similar technologies to:

• Keep you signed in
• Remember your preferences
• Improve website performance
• Analyse platform usage
• Enhance user experience

You may manage cookie preferences through your browser settings.`
  ],

  [
    "Data Security",
    `We implement appropriate technical, administrative and organisational security measures to protect your personal information from unauthorised access, disclosure, alteration or destruction.

However, no online platform can guarantee absolute security.`
  ],

  [
    "Third-Party Services",
    `DigiNiwas may use trusted third-party service providers for services including:

• Payment processing
• Maps and location services
• Cloud hosting
• Analytics
• Customer communication

These providers operate under their own privacy policies.`
  ],

  [
    "Data Retention",
    `We retain your personal information only for as long as necessary to:

• Provide our services
• Meet legal obligations
• Resolve disputes
• Enforce our agreements
• Maintain platform security`
  ],

  [
    "Your Rights",
    `Subject to applicable laws, you may request to:

• Access your personal information
• Update or correct your information
• Delete your account or personal data
• Withdraw certain permissions
• Contact us regarding privacy concerns`
  ],

  [
    "Changes to This Policy",
    `We may update this Privacy Policy from time to time.
The latest version will always be available on the DigiNiwas platform.
Continued use of our services after updates constitutes acceptance of the revised policy.`
  ],

  [
    "Contact Us",
    <>
      <p>
        Email:{" "}
        <a
          href="mailto:diginiwas@gmail.com"
          className="text-[#0F2E46] font-semibold hover:underline"
        >
          diginiwas@gmail.com
        </a>
      </p>
  
      <p className="mt-2">
        Phone:{" "}
        <a
          href="tel:+917988537478"
          className="text-[#0F2E46] font-semibold hover:underline"
        >
          +91-7988537478
        </a>
      </p>
    </>
  ]
].map(([title,body])=>(
          <section key={title} className="bg-white rounded-3xl p-8 shadow-sm border">
            <h2 className="text-2xl font-bold text-[#0F2E46]">{title}</h2>
            <p className="mt-4 text-gray-600 leading-8 whitespace-pre-line">{body}</p>
          </section>
        ))}

        <section className="bg-[#0F2E46] rounded-3xl p-10 text-center text-white">
        <h2 className="text-3xl font-bold">Thank You for Trusting DigiNiwas</h2>

<p className="mt-4 text-white/80 leading-8">

 
  We are committed to building a secure, transparent and intelligent
  property platform for everyone.
</p>
        </section>
      </main>
    </div>
  );
}